# Generated by Django 4.2 on 2026-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninvite',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
