# Generated by Django 4.2 on 2026-02-23 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0003_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='SessionNote',
        ),
    ]
