# Generated by Django 4.2 on 2026-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_rename_note_sessionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
