# Generated by Django 6.0.2 on 2026-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpgsystem',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
