# Generated by Django 4.2 on 2026-02-13 15:14

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.AlterField(
            model_name='character',
            name='sheet_data',
            field=models.JSONField(default=characters.models.get_default_sheet_data),
        ),
    ]
