# Generated by Django 4.2 on 2026-02-25 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0004_rename_note_sessionnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HOSTILE', 'Hostil'), ('FRIENDLY', 'Amigável'), ('NEUTRAL', 'Neutro'), ('MERCHANT', 'Mercador')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.URLField(blank=True, null=True)),
                ('life', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
                'ordering': ['-created_at'],
            },
        ),
    ]
