# Generated by Django 4.2 on 2026-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
