# Generated by Django 6.0.2 on 2026-02-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0005_session_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('durability_current', models.FloatField()),
                ('durability_max', models.FloatField()),
                ('rarity', models.CharField(max_length=100)),
                ('effects', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='session.session')),
            ],
        ),
    ]
